home/urls.py
from django.urls import path

from . import views

app_name = "home"
urlpatterns = [
    # ex: /
    #path("", views.index, name="index"),
    path("", views.index, name="index"),
]

problems/urls.py
from django.urls import path

from . import views

app_name = "problems"
urlpatterns = [
    # problems
    # ex: /problems/
    path("problems/", views.ProblemListView.as_view(), name="problem-list"),
    # ex: /problems/5/
    path("problems/<int:pk>/", views.problem_detail, name="problem-detail"),

    # decks
    # ex: /decks/
    path("decks/", views.DeckListView.as_view(), name="deck-list"),
    # ex: /decks/5/
    path("decks/<int:pk>/", views.DeckDetailView.as_view(), name="deck-detail"),
    # ex /decks/5/practice/
    path('decks/<int:deck_id>/practice/', views.deck_practice, name='deck-practice'),

    # tiptap
    path('tiptap/image-upload/', views.tiptap_image_upload, name='tiptap-image-upload'),
    
]

from django.conf.urls.static import static
from django.conf import settings
# --- Add this section ---
# This is for serving media files during development.
# It is not needed in production, as your web server (e.g., Nginx)
# should be configured to serve media files directly.
#if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
    <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-mml-chtml.js"></script>
</head>
<body>
    <div class="container" style="max-width:600px">
        <div class="row">
            <nav class="navbar navbar-expand-lg bg-body-tertiary">
                <div class="container-fluid">
                    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                        <div class="navbar-nav">
                            <a class="nav-link" href="{% url 'home:index' %}">Home</a>
                            <a class="nav-link" href="{% url 'problems:problem-list' %}">Problems</a>
                            <a class="nav-link" href="{% url 'problems:deck-list' %}">Decks</a>
                        </div>
                    </div>
                </div>
            </nav>          
        </div>
        <div class="row mt-5">
            {% block content %}{% endblock %}
        </div>
    </div>
</body>
</html>